import Link from "next/link";
import { ArrowDown, ArrowRight, MoveUpRight, Plus } from "lucide-react";
import { categories, featuredProducts, products } from "@/lib/products";
import { ProductCard } from "@/components/ProductCard";
import { assetPath } from "@/lib/site";
import { categoryName } from "@/lib/localize";

export function HomePage() {
  return <main>
    <section className="hero"><img className="hero-image" src={assetPath("/images/hero-route.png")} alt="Путешественник у палатки в туманной горной долине" /><div className="hero-shade" /><div className="shell hero-inner"><div className="hero-copy"><p className="eyebrow hero-code">WAYPOINT / 01</p><h1>СЛЕДУЮЩАЯ ТОЧКА<br />ВПЕРЕДИ.</h1><p className="hero-subtitle">Снаряжение для тех, кто всегда знает, куда двигаться дальше.</p><div className="hero-actions"><Link href="/catalog" className="button button-light">Смотреть снаряжение <ArrowRight size={16} /></Link><Link href="/kit" className="button button-quiet">Собрать комплект <Plus size={16} /></Link></div></div><div className="hero-meta"><span>54°42′ N / 20°30′ E</span><span>ВЫСОТА 840 M</span><span>МАРШРУТ 03</span></div></div><a className="hero-scroll" href="#categories"><span>ЛИСТАЙТЕ ДАЛЬШЕ</span><ArrowDown size={16} /></a></section>

    <section className="category-section shell" id="categories"><div className="section-intro"><p className="eyebrow">НАЧНИТЕ С ЗАДАЧИ</p><h2>Выберите<br /><i>направление.</i></h2><p>Не тысячи случайных позиций. Восемь понятных категорий — каждая для следующего решения в маршруте.</p></div><div className="category-list">{categories.map((category) => <Link href={category.href} className="category-row" key={category.name}><small>{category.number}</small><h3>{categoryName(category.name)}</h3><p>{category.description}</p><MoveUpRight size={20} /></Link>)}</div></section>

    <section className="collection-section"><div className="shell collection-header"><div><p className="eyebrow">ПОЛЕВОЙ КОМПЛЕКТ / 48 Ч</p><h2>48 ЧАСОВ<br /><i>ВНЕ ГОРОДА.</i></h2></div><p>Набор для двухдневного маршрута: укрытие, тепло, свет и кухня — без перегруза в рюкзаке.</p><Link href="/kit" className="text-link">Собрать свой комплект <ArrowRight size={15} /></Link></div><div className="shell editorial-grid"><div className="editorial-panel product-feature"><img src={assetPath("/images/ridge-2.png")} alt="Палатка Ridge 2 на светлом фоне" /><div><p className="eyebrow">SHELTER / 02</p><h3>Ridge 2</h3><Link className="text-link" href="/product/ridge-2">Открыть товар <ArrowRight size={15} /></Link></div></div><div className="editorial-panel collection-note"><p className="route-number">02</p><h3>Снаряжение должно оставлять место для самого маршрута.</h3><span>СОБРАНО ДЛЯ СПОКОЙНОЙ ВЫЛАЗКИ</span></div><div className="editorial-panel product-feature dark"><img src={assetPath("/images/field-kit.png")} alt="Компактный набор походной кухни и фонарь" /><div><p className="eyebrow">КУХНЯ + СВЕТ</p><h3>Обустройте небольшой лагерь.</h3><Link className="text-link" href="/catalog?category=Cook">Смотреть снаряжение для лагеря <ArrowRight size={15} /></Link></div></div></div></section>

    <section className="shell featured-section"><div className="section-head"><div><p className="eyebrow">ТЕКУЩАЯ ПОДБОРКА</p><h2>Отобрано<br /><i>для вашего пути.</i></h2></div><Link className="text-link" href="/catalog">Весь каталог <ArrowRight size={15} /></Link></div><div className="product-grid product-grid-three">{featuredProducts.slice(0, 3).map((product, index) => <ProductCard key={product.id} product={product} priority={index === 0} />)}</div></section>

    <section className="kit-callout"><div className="shell kit-callout-inner"><div><p className="eyebrow">СБОРКА МАРШРУТА / 05</p><h2>ВЫ ЗНАЕТЕ,<br />КУДА <i>ЕДЕТЕ.</i><br />МЫ ПОМОЖЕМ<br />ВЫБРАТЬ <i>НУЖНОЕ.</i></h2></div><div><p>Ответьте на пять коротких вопросов — WAYPOINT соберёт функциональный комплект под ваш маршрут, сезон и формат поездки.</p><Link href="/kit" className="button button-light">Собрать комплект <ArrowRight size={16} /></Link><small>ДЕМО-КОНФИГУРАТОР · БЕЗ КОММЕРЧЕСКИХ ОБЕЩАНИЙ</small></div></div></section>

    <section className="shell journal-teaser"><div className="journal-image"><img src={assetPath("/images/hero-route.png")} alt="Туманные горы и лагерь у воды" /><span>ЖУРНАЛ / 03</span></div><div className="journal-copy"><p className="eyebrow">ЖУРНАЛ WAYPOINT</p><h2>Маршрут — это ещё и то, что остаётся <i>после.</i></h2><p>Гиды, короткие планы поездок и разборы вещей, которые действительно стоит брать с собой.</p><Link className="button button-dark" href="/journal">Читать полевые заметки <ArrowRight size={16} /></Link></div></section>

    <section className="shell recently-section"><div className="section-head"><div><p className="eyebrow">ДЛЯ КОРОТКОЙ ВЫЛАЗКИ</p><h2>Ещё одна<br /><i>полезная вещь.</i></h2></div><span className="item-count">{products.length} ТОВАРА В ДЕМО</span></div><div className="product-grid product-grid-four">{products.slice(3, 7).map((product) => <ProductCard key={product.id} product={product} />)}</div></section>
  </main>;
}
