import Link from "next/link";
import { ArrowDown, ArrowRight, MoveUpRight, Plus } from "lucide-react";
import { categories, featuredProducts, products } from "@/lib/products";
import { ProductCard } from "@/components/ProductCard";

export function HomePage() {
  return <main>
    <section className="hero"><img className="hero-image" src="/images/hero-route.png" alt="Путешественник у палатки в туманной горной долине" /><div className="hero-shade" /><div className="shell hero-inner"><div className="hero-copy"><p className="eyebrow hero-code">WAYPOINT / 01</p><h1>THE NEXT POINT<br />IS OUT THERE.</h1><p className="hero-subtitle">Снаряжение для тех, кто всегда знает, куда двигаться дальше.</p><div className="hero-actions"><Link href="/catalog" className="button button-light">Explore gear <ArrowRight size={16} /></Link><Link href="/kit" className="button button-quiet">Build your kit <Plus size={16} /></Link></div></div><div className="hero-meta"><span>54°42′ N / 20°30′ E</span><span>ALTITUDE 840 M</span><span>ROUTE 03</span></div></div><a className="hero-scroll" href="#categories"><span>SCROLL TO EXPLORE</span><ArrowDown size={16} /></a></section>

    <section className="category-section shell" id="categories"><div className="section-intro"><p className="eyebrow">START WITH A NEED</p><h2>Выберите<br /><i>направление.</i></h2><p>Не тысячи случайных позиций. Восемь понятных категорий — каждая для следующего решения в маршруте.</p></div><div className="category-list">{categories.map((category) => <Link href={category.href} className="category-row" key={category.name}><small>{category.number}</small><h3>{category.name}</h3><p>{category.description}</p><MoveUpRight size={20} /></Link>)}</div></section>

    <section className="collection-section"><div className="shell collection-header"><div><p className="eyebrow">FIELD KIT / 48H</p><h2>48 HOURS<br /><i>AWAY.</i></h2></div><p>Набор для двухдневного маршрута: укрытие, тепло, свет и кухня — без перегруза в рюкзаке.</p><Link href="/kit" className="text-link">Собрать свой комплект <ArrowRight size={15} /></Link></div><div className="shell editorial-grid"><div className="editorial-panel product-feature"><img src="/images/ridge-2.png" alt="Палатка Ridge 2 на светлом фоне" /><div><p className="eyebrow">SHELTER / 02</p><h3>Ridge 2</h3><Link className="text-link" href="/product/ridge-2">Посмотреть предмет <ArrowRight size={15} /></Link></div></div><div className="editorial-panel collection-note"><p className="route-number">02</p><h3>Снаряжение должно оставлять место для самого маршрута.</h3><span>CURATED FOR A QUIET EXIT</span></div><div className="editorial-panel product-feature dark"><img src="/images/field-kit.png" alt="Компактный набор походной кухни и фонарь" /><div><p className="eyebrow">COOK + LIGHT</p><h3>Make a small camp.</h3><Link className="text-link" href="/catalog?category=Cook">Explore field tools <ArrowRight size={15} /></Link></div></div></div></section>

    <section className="shell featured-section"><div className="section-head"><div><p className="eyebrow">CURRENT SELECTION</p><h2>Selected for<br /><i>the way ahead.</i></h2></div><Link className="text-link" href="/catalog">Весь каталог <ArrowRight size={15} /></Link></div><div className="product-grid product-grid-three">{featuredProducts.slice(0, 3).map((product, index) => <ProductCard key={product.id} product={product} priority={index === 0} />)}</div></section>

    <section className="kit-callout"><div className="shell kit-callout-inner"><div><p className="eyebrow">ROUTE ASSEMBLY / 05</p><h2>YOU KNOW<br />THE <i>WHERE.</i><br />WE&apos;LL HELP WITH<br />THE <i>WHAT.</i></h2></div><div><p>Ответьте на пять коротких вопросов — WAYPOINT соберёт функциональный комплект под ваш маршрут, сезон и формат поездки.</p><Link href="/kit" className="button button-light">Build your kit <ArrowRight size={16} /></Link><small>DEMO CONFIGURATOR · NO SALES CLAIMS</small></div></div></section>

    <section className="shell journal-teaser"><div className="journal-image"><img src="/images/hero-route.png" alt="Туманные горы и лагерь у воды" /><span>JOURNAL / 03</span></div><div className="journal-copy"><p className="eyebrow">WAYPOINT JOURNAL</p><h2>Маршрут — это ещё и то, что остаётся <i>после.</i></h2><p>Гиды, короткие планы поездок и разборы вещей, которые действительно стоит брать с собой.</p><Link className="button button-dark" href="/journal">Read field notes <ArrowRight size={16} /></Link></div></section>

    <section className="shell recently-section"><div className="section-head"><div><p className="eyebrow">READY FOR A SHORT EXIT</p><h2>One more<br /><i>useful thing.</i></h2></div><span className="item-count">{products.length} DEMO ITEMS</span></div><div className="product-grid product-grid-four">{products.slice(3, 7).map((product) => <ProductCard key={product.id} product={product} />)}</div></section>
  </main>;
}
